//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Attempted account signup.
        /// </summary>
        public static string Email_SubjectAccountAlreadyExists {
            get {
                return ResourceManager.GetString("Email_SubjectAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email address.
        /// </summary>
        public static string Email_SubjectVerifyEmailAddress {
            get {
                return ResourceManager.GetString("Email_SubjectVerifyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were issues with the request and it could not be processed..
        /// </summary>
        public static string General_Error_400BadRequest {
            get {
                return ResourceManager.GetString("General_Error_400BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed as the provided method is not allowed..
        /// </summary>
        public static string General_Error_405MethodNotAllowed {
            get {
                return ResourceManager.GetString("General_Error_405MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed as the provided media type is unsupported..
        /// </summary>
        public static string General_Error_415UnsupportedMediaType {
            get {
                return ResourceManager.GetString("General_Error_415UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already signed into an account. Please sign out before continuing..
        /// </summary>
        public static string General_Error_AlreadyAuthenticated {
            get {
                return ResourceManager.GetString("General_Error_AlreadyAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only valid email addresses are allowed..
        /// </summary>
        public static string General_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("General_Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string General_Error_MissingEmail {
            get {
                return ResourceManager.GetString("General_Error_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be signed in to perform this action..
        /// </summary>
        public static string General_Error_MissingSession {
            get {
                return ResourceManager.GetString("General_Error_MissingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected issue when processing the request. Please try again later..
        /// </summary>
        public static string GeneralServerError {
            get {
                return ResourceManager.GetString("GeneralServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is temporarily unavailable. Please try again later..
        /// </summary>
        public static string GeneralServiceUnavailableError {
            get {
                return ResourceManager.GetString("GeneralServiceUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string GeneralSuccess {
            get {
                return ResourceManager.GetString("GeneralSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account is associated with that email address, you&apos;ll receive a message shortly with further instructions..
        /// </summary>
        public static string Recover_Success_EmailSent {
            get {
                return ResourceManager.GetString("Recover_Success_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully recovered. Set a new password to continue..
        /// </summary>
        public static string Recover_Success_SetNew {
            get {
                return ResourceManager.GetString("Recover_Success_SetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must verify your account email to proceed..
        /// </summary>
        public static string Signup_Error_EmailNotVerified {
            get {
                return ResourceManager.GetString("Signup_Error_EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 12 characters and contain one or more lowercase letters, one or more uppercase letters, one or more numbers, and one or more special characters..
        /// </summary>
        public static string Signup_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Signup_Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired or invalid..
        /// </summary>
        public static string Signup_Error_InvalidToken {
            get {
                return ResourceManager.GetString("Signup_Error_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Signup_Error_MissingPassword {
            get {
                return ResourceManager.GetString("Signup_Error_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required..
        /// </summary>
        public static string Signup_Error_MissingToken {
            get {
                return ResourceManager.GetString("Signup_Error_MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password has already been set for your account. To update it, visit your account settings..
        /// </summary>
        public static string Signup_Error_PasswordAlreadySet {
            get {
                return ResourceManager.GetString("Signup_Error_PasswordAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verified successfully..
        /// </summary>
        public static string Signup_Success_EmailVerified {
            get {
                return ResourceManager.GetString("Signup_Success_EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully set..
        /// </summary>
        public static string Signup_Success_PasswordSet {
            get {
                return ResourceManager.GetString("Signup_Success_PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification link has been sent to the provided email. Click the link in the email message to continue signup..
        /// </summary>
        public static string Signup_VerificationEmailSent {
            get {
                return ResourceManager.GetString("Signup_VerificationEmailSent", resourceCulture);
            }
        }
    }
}
