//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Attempted account signup.
        /// </summary>
        public static string Email_SubjectAccountAlreadyExists {
            get {
                return ResourceManager.GetString("Email_SubjectAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email address.
        /// </summary>
        public static string Email_SubjectVerifyEmailAddress {
            get {
                return ResourceManager.GetString("Email_SubjectVerifyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were issues with the request and it could not be processed..
        /// </summary>
        public static string GeneralBadRequest {
            get {
                return ResourceManager.GetString("GeneralBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only valid email addresses are allowed..
        /// </summary>
        public static string GeneralInvalidEmail {
            get {
                return ResourceManager.GetString("GeneralInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected issue when processing the request. Please try again later..
        /// </summary>
        public static string GeneralServerError {
            get {
                return ResourceManager.GetString("GeneralServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is temporarily unavailable. Please try again later..
        /// </summary>
        public static string GeneralServiceUnavailableError {
            get {
                return ResourceManager.GetString("GeneralServiceUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string GeneralSuccess {
            get {
                return ResourceManager.GetString("GeneralSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 12 characters and contain one or more lowercase letters, one or more uppercase letters, one or more numbers, and one or more special characters..
        /// </summary>
        public static string Signup_ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("Signup_ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired or invalid..
        /// </summary>
        public static string Signup_ErrorInvalidToken {
            get {
                return ResourceManager.GetString("Signup_ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Signup_ErrorMissingEmail {
            get {
                return ResourceManager.GetString("Signup_ErrorMissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Signup_ErrorMissingPassword {
            get {
                return ResourceManager.GetString("Signup_ErrorMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required..
        /// </summary>
        public static string Signup_ErrorMissingToken {
            get {
                return ResourceManager.GetString("Signup_ErrorMissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verified successfully..
        /// </summary>
        public static string Signup_SuccessEmailVerified {
            get {
                return ResourceManager.GetString("Signup_SuccessEmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification link has been sent to the provided email. Click the link in the email message to continue signup..
        /// </summary>
        public static string Signup_VerificationEmailSent {
            get {
                return ResourceManager.GetString("Signup_VerificationEmailSent", resourceCulture);
            }
        }
    }
}
