<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>f99adeaa-737c-4e53-a976-7878b6c633fc</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup>
        <UseCurrentRuntimeIdentifier>false</UseCurrentRuntimeIdentifier>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\SharedResource.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <StronglyTypedFileName>Resources\SharedResource.Designer.cs</StronglyTypedFileName>
            <StronglyTypedModifier>public</StronglyTypedModifier>
            <StronglyTypedClassName>SharedResource</StronglyTypedClassName>
            <StronglyTypedNamespace>API.Resources</StronglyTypedNamespace>
            <PublicClass>true</PublicClass>
            <LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
            <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
        </EmbeddedResource>
    </ItemGroup>

</Project>