<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>f99adeaa-737c-4e53-a976-7878b6c633fc</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Email\Templates\**\*.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>